/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package networkmodeling.client.ui;

/**
 *
 * @author antonlarin
 */
public class HubParametersPanel extends javax.swing.JPanel {

    /**
     * Creates new form HubParametersPanel
     */
    public HubParametersPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        hubDesignatorLabel = new javax.swing.JLabel();
        hubPortsCountLabel = new javax.swing.JLabel();
        hubPortsCountTextField = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        hubDesignatorLabel.setText("Hub paramters:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
        add(hubDesignatorLabel, gridBagConstraints);

        hubPortsCountLabel.setText("Ports count:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        add(hubPortsCountLabel, gridBagConstraints);

        hubPortsCountTextField.setText("8");
        hubPortsCountTextField.setMinimumSize(new java.awt.Dimension(50, 28));
        hubPortsCountTextField.setPreferredSize(new java.awt.Dimension(80, 28));
        hubPortsCountTextField.setSize(new java.awt.Dimension(50, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(hubPortsCountTextField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hubDesignatorLabel;
    private javax.swing.JLabel hubPortsCountLabel;
    private javax.swing.JTextField hubPortsCountTextField;
    // End of variables declaration//GEN-END:variables
}
