/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package networkmodeling.client.ui;

/**
 *
 * @author antonlarin
 */
public class SwitchParametersPanel extends javax.swing.JPanel {

    /**
     * Creates new form SwitchParametersPanel
     */
    public SwitchParametersPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        switchDesignatorLabel = new javax.swing.JLabel();
        switchPortsCountLabel = new javax.swing.JLabel();
        switchPortsCountTextField = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        switchDesignatorLabel.setText("Switch parameters:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
        add(switchDesignatorLabel, gridBagConstraints);

        switchPortsCountLabel.setText("Ports count:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        add(switchPortsCountLabel, gridBagConstraints);

        switchPortsCountTextField.setText("8");
        switchPortsCountTextField.setPreferredSize(new java.awt.Dimension(80, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 66;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(switchPortsCountTextField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel switchDesignatorLabel;
    private javax.swing.JLabel switchPortsCountLabel;
    private javax.swing.JTextField switchPortsCountTextField;
    // End of variables declaration//GEN-END:variables
}
